Exit if any of the tar commands fail

diff --git a/opt/recompose b/opt/recompose
--- a/opt/recompose
+++ b/opt/recompose
@@ -8,6 +8,7 @@ set -m
 
 process_slug() {
   local app_release=${1}
+  local part_number=${2}
 
   echo "--> Processing $app_release"
 
@@ -26,7 +27,10 @@ process_slug() {
 
     if [ -n "$slug_url" ]; then
       echo "--> Downloading slug ${slug_id} for ${app}"
-      curl --retry 3 -s -L "${slug_url}" | tar xzm --strip-components=1 &
+      (
+        curl --retry 3 -s -L "${slug_url}" | tar xzm --strip-components=1
+        echo "$?" > .recompose-part-${part_number}
+      ) &
     else
       echo "! ERROR: could not find slug $slug_id for $app_release"
     fi
@@ -38,7 +42,13 @@ process_slug() {
 wait_for_downloads() {
   local job_count=$1
   local message=$2
-  for i in $(seq 1 1 $job_count); do fg $((i+1)) > /dev/null 2>&1; done
+  for i in $(seq 1 1 $job_count); do
+    fg $((i+1)) > /dev/null 2>&1 # add one because nginx is the first job
+    if [ "$(cat .recompose-part-${i})" != "0" ]; then
+      echo " ! ERROR: Failed to extract part: $(sed -n "${i}p" Appfile)"
+      exit 1
+    fi
+  done
   echo $2
 }
 
@@ -68,8 +78,8 @@ echo "Reading primary parts Appfile..."
 apps=0
 while read app_release; do
   if [ -n "$app_release" ] && [ "$app_release" != "---" ]; then
-    process_slug "$app_release"
     apps=$((apps+1))
+    process_slug "$app_release" "$apps"
   fi
 done </app/Appfile
 
@@ -80,7 +90,7 @@ echo "Reading overlay parts from Appfile..."
 overlay=0
 while read app_release; do
   if [ -n "$app_release" ] && [ $overlay = 1 ]; then
-    process_slug "$app_release"
+    process_slug "$app_release" "$overlay"
   elif [ "$app_release" = "---" ]; then
     overlay=1
   fi
